### ISSUE TITLE
New Microsoft Translate (Azure) bindings not yet working? 

### ISSUE THREAD

**Issue by kiates** [UweKeim/ZetaResourceEditor#26] opened 2017-07-29 18:04 UTC
Trying out your awsome tool and got to the Azure Translate API feature in the hot off the press version 2.3.0.11 7/27/2017.  I can get Quick Translate to work so the Azure API is connected, but every time I try and use "Translate missing languages" it results in the fields being populated with the error message "**** AsyncBridge.Run method threw an exception." instead of the translated text.

Maybe this feature isn't quite done?

**Comment by UweKeim** [comment] 2017-07-30 08:08
I'll take a look.

When I implemented that new Azure Translation API calls, I once came to a similar conclusion as you (does not work), but later on, I never managed to reproduce this behaviour again.

Strange...

**Comment by UweKeim** [comment] 2017-08-09 21:16
I've just debugged it and _cannot_ see an error.

My Microsoft Translator (Azure) client secret looks similar to:

> 53071fg63970211ef37a312399f8a951

If the exception occurs on your machine, could you post it here, including all inner exceptions?

In addition, if you like, send me your client secret by [e-mail](mailto:uwe.keim+github@gmail.com) and I can use it to debug the application again.

**Comment by jusovsky** [comment] 2017-08-17 17:08
I found that there are multiple issues, here. 
**1.**
`@"<ContentType xmlns=""http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2"">{0}</ContentType>" +`
Should be
`@"<ContentType xmlns=""http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2"">text/plain</ContentType>" +`
**2.**
There's an unhandled NRE thrown from 
`A.Run(response?.Content.ReadAsStringAsync(), res => responseBody = res);`
This method runs before the request has completed.  This can be fixed easily with a continuation or async-await.  I'm not familiar with AsyncHelper, but I tried using two different AsyncBridge objects and it worked fine.  

**3.**
I think the TranslateArray method might just be broken on Azure right now.  A few people complained of this same issue in December 2016.  The bug on Connect is marked as "Resolved," but I strongly suspect it came back.

Thank you,
Josh Usovsky

**Comment by kiates** [comment] 2017-08-18 01:38
I was able to try again today, and get the same brief error message placed into each previously empty string. "**** AsyncBridge.Run method threw an exception."

I tried your API secret and it wouldn't connect (You said it's similar so maybe you were just illustrating what it looks like?)

I don't get an exception stack trace (unless it is logged somewhere I don't know about), so it must catch it internally.  I can't easily debug further on my end since I don't have DevExpress components.

I'll send you the key to debug if you think it will be helpful.

Thank you!

**Comment by UweKeim** [comment] 2017-08-18 06:49
Thanks, @jusovsky I fixed **1.** and **2.** (at least I do hope). Maybe **2.** is also the cause for the issue, that @kiates gets. (You API secret works well for me in my tests).

Anyway, I just released a new version **2.3.0.15**. [Here is the direct setup download](http://zeta.li/zre-download-setup).

**Comment by jusovsky** [comment] 2017-08-18 14:58
Thank you, @UweKeim!  That fixed it.   
Chad, if you install the application, you can just redirect the references to the binaries in the install folder.  That's how I was able to build it.
@UweKeim, Someday you might want to put all of the dependencies into a Nuget package so that it's easier for others to build.  In fact, I'd be happy to do that for you, if you'd like.

**Comment by kiates** [comment] 2017-08-18 19:01
@UweKeim Great. I installed the new version and it looks like it fixed it! Thank you! @jusovsky Thanks for the tip on the dependencies; I thought it would require more than just the run-time versions.

**Comment by UweKeim** [comment] 2017-08-20 15:26
@jusovsky I cannot legally deploy DevExpress assemblies. You need to own a license to build Zeta Resource Editor.

**Closed** 2017-08-20 15:27 UTC
